# Generated by Django 4.2.4 on 2023-09-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('nome', models.TextField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('razao', models.TextField(max_length=255)),
                ('cnpj', models.IntegerField(primary_key=True, serialize=False)),
                ('endereco', models.TextField(max_length=255)),
                ('celular', models.IntegerField()),
            ],
        ),
    ]
